version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - chatnet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/messages"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chatnet

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://backend:8000
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge